###############################################################################
# Copyright (C) 2023, Advanced Micro Devices, Inc.  All rights reserved.
# SPDX-License-Identifier: MIT
###############################################################################

enable_beta_device *

create_project -name vck190_power1 -force -dir ../hwflow_vck190_power1 -part xcvc1902-vsva2197-2MP-e-S

set part xcvc1902-vsva2197-2MP-e-S

set proj_name vck190_power1
set proj_dir hwflow_vck190_power1
set bd_tcl_dir hwflow_vck190_power1/outputs
set board vck190
set device vc1902
set rev es1
set output {xsa bit}
set xdc_list {./xdc/vck190_ddr4single_dimm1.xdc ./xdc/vck190.xdc ./xdc/pl_clk_uncertainty.xdc ./xdc/default.xdc}
set ip_repo_path {./ip}
set src_repo_path {./src}


import_files -fileset constrs_1 $xdc_list


set_property ip_repo_paths $ip_repo_path [current_project]
update_ip_catalog

# Create block diagram design and set as current design
set design_name $proj_name
create_bd_design $proj_name
current_bd_design $proj_name

# Set current bd instance as root of current design
set parentCell [get_bd_cells /]
set parentObj [get_bd_cells $parentCell]
current_bd_instance $parentObj

### Enabling PR flow
set_param project.enable2RP 1
set_param project.enablePRFlowIPI 1
set_param project.enablePRFlowIPIOOC 1
set_param chipscope.enablePRFlow 1
set_param hd.enablePR 2591
set_param bitstream.enablePR 8519
set_param project.enableReferenceBd true
set_property PR_FLOW true [current_project]
set_param bitstream.enableMetaData 1
set_param noc.enableNOCClockGating 0
#set_param bitstream.enableDdrModelData 1

source ../$proj_dir/config_bd.tcl
save_bd_design

assign_bd_address

create_main_reconfig_partitions
current_bd_design $proj_name


make_wrapper -files [get_files ../$proj_dir/${proj_name}.srcs/sources_1/bd/$proj_name/${proj_name}.bd] -top
import_files -force -norecurse ../$proj_dir/${proj_name}.srcs/sources_1/bd/$proj_name/hdl/${proj_name}_wrapper.v
update_compile_order
set_property top ${proj_name}_wrapper [current_fileset]
update_compile_order -fileset sources_1


save_bd_design
validate_bd_design
generate_target all [get_files ../$proj_dir/${proj_name}.srcs/sources_1/bd/$proj_name/${proj_name}.bd]
file mkdir ../$bd_tcl_dir


set fd [open ../$bd_tcl_dir/README.hw w]

puts $fd "##########################################################################"
puts $fd "This is a brief document containing design specific details for : ${board}"
puts $fd "This is auto-generated by Petalinux ref-design builder created @ [clock format [clock seconds] -format {%a %b %d %H:%M:%S %Z %Y}]"
puts $fd "##########################################################################"

set board_part [get_board_parts [current_board_part -quiet]]
if { $board_part != ""} {
	puts $fd "BOARD: $board_part"
}

set design_name [get_property NAME [get_bd_designs]]
puts $fd "BLOCK DESIGN: $design_name"


set columns {%40s%30s%15s%50s}
puts $fd [string repeat - 150]
puts $fd [format $columns "MODULE INSTANCE NAME" "IP TYPE" "IP VERSION" "IP"]
puts $fd [string repeat - 150]

foreach ip [get_ips] {
	set catlg_ip [get_ipdefs -all [get_property IPDEF $ip]]
	puts $fd [format $columns [get_property NAME $ip] [get_property NAME $catlg_ip] [get_property VERSION $catlg_ip] [get_property VLNV $catlg_ip]]
}

close $fd

#######################DFX Configuration#####################################
create_pr_configuration -name config_full -partitions [list vck190_power1_i/slot0:slot0_inst_0 ]
create_pr_configuration -name config_gb -partitions { }  -greyboxes [list vck190_power1_i/slot0 ]
create_run impl_full -parent_run synth_1 -flow {Vivado Implementation 2023} -pr_config config_full -dfx_mode STANDARD
set_property PR_CONFIGURATION config_full [get_runs impl_full]
create_run impl_gb -parent_run impl_full -flow {Vivado Implementation 2023} -pr_config config_gb
#############################################################################

set_property synth_checkpoint_mode Hierarchical [get_files ../$proj_dir/${proj_name}.srcs/sources_1/bd/$proj_name/${proj_name}.bd]
launch_runs synth_1 -jobs 12
wait_on_run synth_1


launch_runs impl_1 -to_step write_device_image -jobs 12

wait_on_run impl_1


file copy -force ../$proj_dir/${proj_name}.runs/impl_1/${proj_name}_wrapper.rcdo ../$bd_tcl_dir/${proj_name}.rcdo
file copy -force ../$proj_dir/${proj_name}.runs/impl_1/${proj_name}_wrapper.rnpi ../$bd_tcl_dir/${proj_name}.rnpi

file copy -force ../$proj_dir/${proj_name}.runs/impl_1/${proj_name}_wrapper.pdi ../$bd_tcl_dir/${proj_name}.pdi
file copy -force ../$proj_dir/${proj_name}.runs/impl_1/gen_files ../$bd_tcl_dir/
file copy -force ../$proj_dir/${proj_name}.runs/impl_1/static_files ../$bd_tcl_dir/

set_property platform.board_id $proj_name [current_project]

set_property platform.ip_cache_dir [get_property ip_output_repo [current_project]] [current_project]

set_property platform.platform_state "impl" [current_project]

set_property platform.name $proj_name [current_project]

set_property platform.vendor "xilinx" [current_project]

set_property platform.version "1.0" [current_project]

open_run impl_1
write_hw_platform -fixed -force -include_bit -file ../$bd_tcl_dir/${proj_name}.xsa
validate_hw_platform -verbose ../$bd_tcl_dir/${proj_name}.xsa
open_checkpoint ../$proj_dir/${proj_name}.runs/impl_1/${proj_name}_wrapper_routed_bb.dcp
write_device_image ../$bd_tcl_dir/vck190_base_wrapper_out
